version: '3'

services:
#  frontend:
#    image: ror0noaz0ro81/clinic_frontend:1.0.1
#    build:
#      context: ./clinic_administrative_frontend
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    env_file:
#      - ./clinic_administrative_frontend/.env.production
#    depends_on:
#      - backend
#      - db
#    links:
#      - backend
#      - db

  backend:
    container_name: bumscan-backend
    build:
      context: ./bumscan_backend
      dockerfile: Dockerfile
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: bumscan-psql
    image: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bumscan_db
      - POSTGRES_USER=bumscan
      - POSTGRES_PASSWORD=Sadeghi81

volumes:
  postgres_data: