# Generated by Django 5.0.3 on 2024-03-09 20:00

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='عنوان')),
                ('instructions', models.TextField(verbose_name='دستورالعمل')),
                ('first_image', models.ImageField(blank=True, null=True, upload_to=api.models.image_file_path, verbose_name='عکس و فایل')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to=api.models.image_file_path, verbose_name='عکس و فایل')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to=api.models.image_file_path, verbose_name='عکس و فایل')),
                ('first_str_lvl', models.IntegerField(help_text='kg')),
                ('second_str_lvl', models.IntegerField(help_text='kg')),
                ('third_str_lvl', models.IntegerField(help_text='kg')),
                ('fourth_str_lvl', models.IntegerField(help_text='kg')),
                ('fifth_str_lvl', models.IntegerField(help_text='kg')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.image_file_path, verbose_name='عکس')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='عنوان گروه')),
                ('related_exercises', models.ManyToManyField(to='api.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_muscle', to='api.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_muscle', to='api.muscle'),
        ),
    ]
